[general]
import = [
    "~/.config/alacritty/themes/themes/baitong.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 160, lines = 64 }
position = { x = 0, y = 0 }
padding = { x = 5, y = 5 }

[colors]
primary.background = "#181818"
bright.black = "#999999"
cursor = { text = "CellBackground", cursor = "CellForeground" }

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Regular" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold" }
size = 16

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t/@-."

[keyboard]
bindings = [
    { key = "Return", mods = "Shift", chars = "\n" } 
]
